name: Obituaries
version: @VERSION@
description: Describes player death events
author: EdGruberman (ed@rjump.com)
main: edgruberman.bukkit.obituaries.Main
commands:
    'obituaries:reload':
        description: Reload Obituaries plugin
        permission: obituaries.reload
permissions:
    obituaries.reload:
        description: Can use reload command
        default: op