default: '%1$s died'
DamageCause:
    ENTITY_ATTACK: '%1$s was slain by %2$s'
    PROJECTILE: '%1$s was shot by %2$s'
    ENTITY_EXPLOSION: '%1$s blew up with %2$s'
    BLOCK_EXPLOSION: '%1$s blew up in %2$s'
    CONTACT: '%1$s died from touching %2$s'
    SUFFOCATION: '%1$s suffocated in %2$s'
    LIGHTNING: '%1$s died from being struck by %2$s'
    FALL: '%1$s hit the ground too hard after falling %2$s blocks'
    SUICIDE: '%1$s committed suicide'
    FIRE: '%1$s went up in flames'
    FIRE_TICK: '%1$s burned to death after being lit by %2$s'
    LAVA: '%1$s tried to swim in lava'
    DROWNING: '%1$s drowned'
    VOID: '%1$s fell out of the world'
    STARVATION: '%1$s starved to death'
    CUSTOM: '%1$s died'
weapon: '%1$s with %2$s'
hand: 'a bare fist'
enchanted: ' that is enchanted'
owners:
    Projectile: '%2$s with %1$s'
    Tameable: '%1$s tamed by %2$s'
    Vehicle: '%1$s ridden by %2$s'
Entity:
    Chicken: a chicken
    Cow: a cow
    Creeper: a creeper
    PoweredCreeper: an electrified creeper
    Ghast: a ghast
    Giant: a giant
    PigZombie: a zombie pigman
    Sheep: a sheep
    Skeleton: a skeleton
    Slime: a slime
    Spider: a spider
    Squid: a squid
    Zombie: a zombie
    TNTPrimed: TNT
    PoweredMinecart: a powered minecart
    StorageMinecart: a storage minecart
    LightningStrike: a lightning strike
    Pig: a pig
    Wolf: a wolf
    Arrow: an arrow
    Egg: an egg
    Fireball: a fireball
    Fish: a fish
    Snowball: a snowball
    Boat: a boat
    Minecart: a minecart
    Enderman: an enderman
    ExperienceOrb: an experience orb
    CaveSpider: a cave spider
    FallingSand: falling sand
    Silverfish: a silverfish
    MagmaCube: a magma cube
    Blaze: a blaze
    EnderDragon: an ender dragon
    Villager: a villager
    Mooshroom: a mooshroom
Material:
    AIR: air
    STONE: stone
    GRASS: grass
    DIRT: dirt
    COBBLESTONE: cobblestone 
    WOOD: wood
    SAPLING: a sapling
    BEDROCK: bedrock
    WATER: water
    STATIONARY_WATER: water 
    LAVA: lava
    STATIONARY_LAVA: lava 
    SAND: sand
    GRAVEL: gravel
    GOLD_ORE: gold ore
    IRON_ORE: iron ore
    COAL_ORE: coal ore
    LOG: wood
    LEAVES: leaves
    SPONGE: a sponge
    GLASS: glass
    LAPIS_ORE: lapis lazuli ore
    LAPIS_BLOCK: a lapis lazuli block
    DISPENSER: a dispenser
    SANDSTONE: sandstone
    NOTE_BLOCK: a note block
    BED_BLOCK: a bed
    POWERED_RAIL: a powered rail
    DETECTOR_RAIL: a detector rail
    PISTON_STICKY_BASE: a piston sticky base 
    WEB: a web
    LONG_GRASS: dead grass
    DEAD_BUSH: a dead shrub
    PISTON_BASE: a piston base
    PISTON_EXTENSION: a piston extension
    WOOL: wool
    PISTON_MOVING_PIECE: a piston moving piece 
    YELLOW_FLOWER: a yellow flower
    RED_ROSE: a red rose
    BROWN_MUSHROOM: a brown mushroom
    RED_MUSHROOM: a red mushroom
    GOLD_BLOCK: a gold block
    IRON_BLOCK: an iron block
    DOUBLE_STEP: a double slab
    STEP: a slab
    BRICK: brick
    TNT: TNT
    BOOKSHELF: a bookshelf 
    MOSSY_COBBLESTONE: mossy cobblestone
    OBSIDIAN: obsidian
    TORCH: a torch
    FIRE: fire
    MOB_SPAWNER: a mob spawner 
    WOOD_STAIRS: wood stairs
    CHEST: a chest
    REDSTONE_WIRE: a redstone wire
    DIAMOND_ORE: diamond ore
    DIAMOND_BLOCK: a diamond block
    WORKBENCH: a crafting bench
    CROPS: crops
    SOIL: soil
    FURNACE: a furnace
    BURNING_FURNACE: a burning furnace
    SIGN_POST: a sign post
    WOODEN_DOOR: a wood door
    LADDER: a ladder
    RAILS: rails
    COBBLESTONE_STAIRS: cobblestone stairs 
    WALL_SIGN: a wall sign
    LEVER: a lever
    STONE_PLATE: a stone pressure plate
    IRON_DOOR_BLOCK: an iron door
    WOOD_PLATE: a wood pressure plate
    REDSTONE_ORE: redstone ore
    GLOWING_REDSTONE_ORE: glowing redstone ore
    REDSTONE_TORCH_OFF: a redstone torch
    REDSTONE_TORCH_ON: a redstone torch
    STONE_BUTTON: a stone button
    SNOW: snow
    ICE: ice
    SNOW_BLOCK: a snow block 
    CACTUS: cactus
    CLAY: clay
    SUGAR_CANE_BLOCK: a sugar cane block 
    JUKEBOX: a jukebox
    FENCE: a fence
    PUMPKIN: a pumpkin
    NETHERRACK: netherrack
    SOUL_SAND: soul sand
    GLOWSTONE: glowstone
    PORTAL: a portal
    JACK_O_LANTERN: a jack o' lantern block
    CAKE_BLOCK: a cake block
    DIODE_BLOCK_OFF: a diode
    DIODE_BLOCK_ON: a diode
    LOCKED_CHEST: a locked chest
    TRAP_DOOR: a trap door
    MONSTER_EGGS: a silverfish egg block
    SMOOTH_BRICK: stone brick
    HUGE_MUSHROOM_1: a huge brown mushroom block
    HUGE_MUSHROOM_2: a huge red mushroom block
    IRON_FENCE: iron bars
    THIN_GLASS: a glass pane
    MELON_BLOCK: a melon
    PUMPKIN_STEM: a pumpkin stem
    MELON_STEM: a melon stem
    VINE: a vine
    FENCE_GATE: a fence gate
    BRICK_STAIRS: brick stairs
    SMOOTH_STAIRS: stone stairs
    MYCEL: mycellium
    WATER_LILY: a lily pad
    NETHER_BRICK: nether brick
    NETHER_FENCE: a nether fence
    NETHER_BRICK_STAIRS: nether brick stairs
    NETHER_WARTS: a nether wart
    ENCHANTMENT_TABLE: an enchantment table
    BREWING_STAND: a brewing stand
    CAULDRON: a cauldron
    ENDER_PORTAL: an ender portal
    ENDER_PORTAL_FRAME: an ender portal frame
    ENDER_STONE: an ender stone
    DRAGON_EGG: a dragon egg
    IRON_SPADE: an iron shovel
    IRON_PICKAXE: an iron pickaxe
    IRON_AXE: an iron axe
    FLINT_AND_STEEL: flint and steel
    APPLE: an apple
    BOW: a bow
    ARROW: an arrow
    COAL: coal
    DIAMOND: diamond
    IRON_INGOT: an iron ingot
    GOLD_INGOT: a gold ingot
    IRON_SWORD: an iron sword
    WOOD_SWORD: a wood sword
    WOOD_SPADE: a wood shovel
    WOOD_PICKAXE: a wood pickaxe
    WOOD_AXE: a wood axe
    STONE_SWORD: a stone sword
    STONE_SPADE: a stone shovel
    STONE_PICKAXE: a stone pickaxe
    STONE_AXE: a stone axe
    DIAMOND_SWORD: a diamond sword
    DIAMOND_SPADE: a diamond shovel
    DIAMOND_PICKAXE: a diamond pickaxe
    DIAMOND_AXE: a diamond axe
    STICK: a stick
    BOWL: a bowl
    MUSHROOM_SOUP: mushroom soup
    GOLD_SWORD: a gold sword
    GOLD_SPADE: a gold shovel
    GOLD_PICKAXE: a gold pickaxe
    GOLD_AXE: a gold axe
    STRING: string
    FEATHER: a feather
    SULPHUR: gunpowder
    WOOD_HOE: a wood hoe
    STONE_HOE: a stone hoe
    IRON_HOE: an iron hoe
    DIAMOND_HOE: a diamond hoe
    GOLD_HOE: a gold hoe
    SEEDS: seeds
    WHEAT: wheat
    BREAD: bread
    LEATHER_HELMET: a leather helmet
    LEATHER_CHESTPLATE: a leather chestplate
    LEATHER_LEGGINGS: leather leggings
    LEATHER_BOOTS: leather boots
    CHAINMAIL_HELMET: a chainmail helmet
    CHAINMAIL_CHESTPLATE: a chainmail chestplate
    CHAINMAIL_LEGGINGS: chainmail leggings
    CHAINMAIL_BOOTS: chainmail boots
    IRON_HELMET: an iron helmet
    IRON_CHESTPLATE: an iron chestplate
    IRON_LEGGINGS: iron leggings
    IRON_BOOTS: iron boots
    DIAMOND_HELMET: a diamond helmet
    DIAMOND_CHESTPLATE: a diamond chestplate
    DIAMOND_LEGGINGS: diamond leggings
    DIAMOND_BOOTS: diamond boots
    GOLD_HELMET: a gold helmet
    GOLD_CHESTPLATE: a gold chestplate
    GOLD_LEGGINGS: gold leggings
    GOLD_BOOTS: gold boots
    FLINT: flint
    PORK: pork
    GRILLED_PORK: grilled pork 
    PAINTING: a painting
    GOLDEN_APPLE: a golden apple
    SIGN: a sign
    WOOD_DOOR: a wood door
    BUCKET: a bucket
    WATER_BUCKET: a water bucket
    LAVA_BUCKET: a lava bucket
    MINECART: a minecart
    SADDLE: a saddle
    IRON_DOOR: an iron door
    REDSTONE: redstone dust
    SNOW_BALL: a snow ball
    BOAT: a boat
    LEATHER: leather
    MILK_BUCKET: a milk bucket
    CLAY_BRICK: a clay brick
    CLAY_BALL: a clay ball
    SUGAR_CANE: a sugar cane
    PAPER: paper
    BOOK: a book
    SLIME_BALL: a slime ball
    STORAGE_MINECART: a storage minecart
    POWERED_MINECART: a powered minecart
    EGG: an egg
    COMPASS: a compass
    FISHING_ROD: a fishing rod
    WATCH: a clock
    GLOWSTONE_DUST: glowstone dust
    RAW_FISH: a raw fish
    COOKED_FISH: a cooked fish
    INK_SACK: an ink sac
    BONE: a bone
    SUGAR: sugar
    CAKE: a cake
    BED: a bed
    DIODE: a diode
    COOKIE: a cookie
    MAP: a map 
    SHEARS: shears
    MELON: a melon
    PUMPKIN_SEEDS: pumpkin seeds
    MELON_SEEDS: melon seeds
    RAW_BEEF: raw beef
    COOKED_BEEF: a steak
    RAW_CHICKEN: raw chicken
    COOKED_CHICKEN: a cooked chicken
    ROTTEN_FLESH: rotten flesh
    ENDER_PEARL: an ender pearl
    BLAZE_ROD: a blaze rod
    GHAST_TEAR: a ghast tear
    GOLD_NUGGET: a gold nugget
    NETHER_STALK: a nether wart
    POTION: a potion
    GLASS_BOTTLE: a glass bottle
    SPIDER_EYE: a spider eye
    FERMENTED_SPIDER_EYE: a fermented spider eye
    BLAZE_POWDER: blaze powder
    MAGMA_CREAM: magma cream
    BREWING_STAND_ITEM: a brewing stand
    CAULDRON_ITEM: a cauldron
    EYE_OF_ENDER: an eye of ender
    SPECKLED_MELON: a gilstering melon
    GOLD_RECORD: a gold disc
    GREEN_RECORD: a green disc
    RECORD_3: an orange disc
    RECORD_4: a red disc
    RECORD_5: a lime green disc
    RECORD_6: a purple disc
    RECORD_7: a violet disc
    RECORD_8: a black disc
    RECORD_9: a white disc
    RECORD_10: a sea green disc
    RECORD_11: a broken disc
MaterialData:
    "SAPLING:0": an oak sapling
    "SAPLING:1": a spruce sapling
    "SAPLING:2": a birch sapling
    "LOG:0": oak wood
    "LOG:1": spruce wood
    "LOG:2": birch wood
    "LEAVES:0": oak leaves
    "LEAVES:1": spruce leaves
    "LEAVES:2": birch leaves
    "LONG_GRASS:0": dead grass
    "LONG_GRASS:1": tall grass
    "LONG_GRASS:2": a live shrub
    "WOOL:0": white wool
    "WOOL:1": orange wool
    "WOOL:2": magenta wool
    "WOOL:3": light blue wool
    "WOOL:4": yellow wool
    "WOOL:5": light green wool
    "WOOL:6": pink wool
    "WOOL:7": gray wool
    "WOOL:8": light gray wool
    "WOOL:9": cyan wool
    "WOOL:10": purple wool
    "WOOL:11": blue wool
    "WOOL:12": brown wool
    "WOOL:13": dark green wool
    "WOOL:14": red wool
    "WOOL:15": black wool
    "DOUBLE_STEP:0": a double stone slab
    "DOUBLE_STEP:1": a double sandstone slab
    "DOUBLE_STEP:2": a double wooden slab
    "DOUBLE_STEP:3": a double cobblestone slab
    "STEP:0": a stone slab
    "STEP:1": a sandstone slab
    "STEP:2": a wooden slab
    "STEP:3": a cobblestone slab
    "COAL:0": coal
    "COAL:1": charcoal
    "SMOOTH_BRICK:0": stone brick
    "SMOOTH_BRICK:1": mossy stone brick
    "SMOOTH_BRICK:2": cracked stone brick
    "INK_SACK:0": an ink sac
    "INK_SACK:1": rose red
    "INK_SACK:2": cactus green
    "INK_SACK:3": cocoa beans
    "INK_SACK:4": lapis lazuli dye
    "INK_SACK:5": purple dye
    "INK_SACK:6": cyan dye
    "INK_SACK:7": light gray dye
    "INK_SACK:8": gray dye
    "INK_SACK:9": pink dye
    "INK_SACK:10": lime dye
    "INK_SACK:11": dandelion yellow
    "INK_SACK:12": light blue dye
    "INK_SACK:13": magenta dye
    "INK_SACK:14": orange dye
    "INK_SACK:15": bone meal
    "MONSTER_EGGS:0": a silverfish stone egg block
    "MONSTER_EGGS:1": a silverfish cobblestone egg block
    "MONSTER_EGGS:2": a silverfish brick egg block